# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - skip: true

release:
  draft: true

changelog:
  sort: asc
