name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    env:
      CGO_ENABLED: 0
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: cache-go-${{ runner.os }}-1.15.x-${{ github.run_number }}
          restore-keys: |
            cache-go-${{ runner.os}}-1.19.x-

      - name: Build
        run: make build-all

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Refresh GoReport
        run: curl -XPOST --data 'repo=github.com/darthPestilane/easytcp' 'https://goreportcard.com/checks'

  test:
    needs: lint
    env:
      GO111MODULE: on
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        go-version: [1.17.x, 1.18.x, 1.19.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version}}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version}}

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/Library/Caches/go-build
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: cache-go-${{ runner.os }}-${{ matrix.go-version }}-${{ github.run_number }}
          restore-keys: |
            cache-go-${{ runner.os }}-${{ matrix.go-version }}-

      - name: Test
        run: make test-v

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .testCoverage.txt
