name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  lint:
    env:
      CGO_ENABLED: 0
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: lint-cache
          restore-keys: lint-cache-restore

      - name: Build
        run: make build-all

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Refresh GoReport
        run: curl -XPOST --data 'repo=github.com/darthPestilane/easytcp' 'https://goreportcard.com/checks'

  test:
    needs: lint
    env:
      GO111MODULE: on
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go-version: [ 1.14.x, 1.15.x, 1.16.x, 1.17.x ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version}}

      - name: Cache Linux
        uses: actions/cache@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: test-cache-${{ matrix.os }}-${{ matrix.go-version }}
          restore-keys: test-cache-${{ matrix.os }}-${{ matrix.go-version }}-restore

      - name: Cache Macos
        uses: actions/cache@v2
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: test-cache-${{ matrix.os }}-${{ matrix.go-version }}
          restore-keys: test-cache-${{ matrix.os }}-${{ matrix.go-version }}-restore

      - name: Cache Windows
        uses: actions/cache@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          path: |
            %LocalAppData%\go-build
            ~/go/pkg/mod
          key: test-cache-${{ matrix.os }}-${{ matrix.go-version }}
          restore-keys: test-cache-${{ matrix.os }}-${{ matrix.go-version }}-restore

      - name: Test
        run: make test-v

      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: .testCoverage.txt
